name: localstore
description: A JSON file-based storage package provides a persistent repository for simple NoSQL database.

version: 1.3.6
homepage: https://github.com/chuyentt/localstore

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
